DESTINATIONS = {
    "ADMIN": "00_ADMIN",
    "FINANCE": "01_FINANCE",
    "CAREER": "02_CAREER",
    "ENGINEERING": "03_ENGINEERING",
    "PROJECTS": "04_PROJECTS",
    "PERSONAL": "05_PERSONAL",
    "MEDIA": "06_MEDIA",
    "ARCHIVE": "90_ARCHIVE",
    "INBOX": "_INBOX_REVIEW",
}